backend:
  name: git-gateway
  # repo: "davidroyer/got2dance"
  branch: netlifycms

media_folder: src/static/cms-uploads
public_folder: '/cms-uploads'

collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Lessons Page"
        name: "lessons"
        file: "_CMS/content/lessons.yml"
        fields:
          # - {label: Title, name: title, widget: string}
          - label: Packages
            name: packages
            widget: list
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Amount, name: amount, widget: string}

      - label: "About Page"
        name: "about"
        file: "_CMS/content/about.yml"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: markdown}
          - label: Team
            name: team
            widget: list
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Position, name: position, widget: string}
              - {label: Photo, name: photo, widget: image}

      - label: "Locations Page"
        name: "locations"
        file: "_CMS/content/locations.yml"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: markdown}
          - label: Locations
            name: locations
            widget: list
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Address, name: address, widget: string}
              
      - label: "Weddings Page"
        name: "weddings"
        file: "_CMS/content/weddings.json"
        fields:
          - label: Packages
            name: packages
            widget: list
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Level, name: level, widget: string}
              - {label: Amount, name: amount, widget: string}                
